import Head from "next/head";
import styles from "../styles/Home.module.css";
import UserCard from "../components/userCard";
import Link from "next/link";
import useSWR from "swr";

const defaultEndPoint = "http://localhost:9000/api/v1/users";

// const fetcher = (...args) => fetch(...args).then((res) => res.json());

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(defaultEndPoint);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default function Home({ data }) {
  return (
    <Link href="/">
      <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="min-h-screen pt-12 bg-background  pr-0 flex-1 flex-col content-start items-center">
          <div>
            <div className="text-center">
              <h1 className="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600">
                Bienvenido al listado de usuarios....!
              </h1>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Quisquam voluptatem, doloremque, quia quod quibusdam, dolore
                dolorum voluptatibus quaerat, quam doloremque quisquam dolorum
                quisquam
              </p>
            </div>
            <ul className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4 pt-12 px-12">
              {data.users.map((user, index) => (
                <UserCard user={user} key={index} />
              ))}
            </ul>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" Grupo 9 "}
          </a>
        </footer>
      </div>
    </Link>
  );
}
